apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- kubeflow-gateway.yaml
- deny_all_authorizationpolicy.yaml
- gateway_authorizationpolicy.yaml
- kubeflow-cluster-roles.yaml
