apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
## Common
# - argocd-applications/metallb.yaml
# - argocd-applications/rook-ceph.yaml
# - argocd-applications/nginx.yaml
# - argocd-applications/nvidia-gpu-operator.yaml
- argocd-applications/istio-operator.yaml
- argocd-applications/istio.yaml    
- argocd-applications/istio-resources.yaml
# - argocd-applications/knative.yaml

# Pick *one* of the following applications
- argocd-applications/argocd.yaml
# - argocd-applications/argocd-private-repo.yaml

# Pick *one* of the following applications 
- argocd-applications/cert-manager-self-signing.yaml
# - argocd-applications/cert-manager-dns-01.yaml

# Pick *one* of the following
- argocd-applications/certificates.yaml
# - argocd-applications/certificates-imported.yaml
