kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: git-repo-secret
  namespace: argocd
  creationTimestamp: null
spec:
  template:
    metadata:
      name: git-repo-secret
      namespace: argocd
      creationTimestamp: null
    data: null
  encryptedData:
    HTTPS_PASSWORD: AgB/H7sTUTzBWylkhGHbQey/sELopPGSccmllIlvrE1uyFxMECaSIyK0jpr4yg1Cv8HVxIe3qXFNrHRSm+oKyNDWpFnDHX0DQ/+l1fGvzK80uWQBOI4QZDC0Hbz0jIBNqkJikM4BToSVWUUba8z26vQL8ANtdtfVgzLRCqQ46wQ6+jelb/NvNLNkpm4/5mdaxxQMn3td+vhE+hUbaDuXfMX0056PkIMGEOf7Eu05GWfCWUbCJS/DA4dmO/NKE6RcBRBSX3aYjTE9/U+PZCCk08fO4q5iemHVf5W/KXX+rUaVV6isD/yx3bhcCjDiDeTtmtZL2iXmvTa3npXgl0yHvhdgz17VD6cxRkrR3hHaX/YJIkNb8EBGLtmM63gV5fUx15yN1E070TcnpCLvDr/2TwxO+W6Y6UtXujmQQuC6KFybwtGEt6ShydlBBc7uIGS78lbSubxfd+VF+bHV1Z1LhHgV99+Ma4+ZGqhchnckk03EQV+YMSABng6/ASwOuFRgQDVIMlWe6FozBd4P6pKtV4AN7tWf+0cqBP/rW/nDMr+VLbJ74hW7LLo1JCCVeEpidjlDJh55NSekAoz+8DjMtgs9s/e3xnEkB4y+pcGwcnI5P7BcLbsL5DaKmLot3xhwlPe5z+t7R2ReS00mLz/RC+Cj93y76TrveX4eogs4Dlnb8C5Ybb006lGtBJamLRzntE0=
    HTTPS_USERNAME: AgAh4gGCfZL3lqrdcHfT74iaA/kmwPktP1ffh1r+/za3zGf1ImUoDGVrz43RjYfMJUxGrbeOljmRdxjz+Syaxu7EgytNUpG5uH4BXOUc1R12mPx+qPusvq5Mi+5sdR9+gUKWa/jmuNDjAneMewe+rLsi5+g44FD4h6oCGCDNPlS14gEgWAFa7pEGaKAZ1F/pwegYS3/808hj533F5wsxi6JtMTyqxjtlnUBhzZ9aNgcYorbMZfABu88BAlBVnW6/5F6oqKIu9udUSp7fvF+Cid+7HAgyybO7nEHiYDin46JATqjsf+1sA6+SEXhqwe0+9mAWrlnyJ3kOReEh53vlCuSmQCbTRmtrExMbRYjdscSH6w+pjOup+Fu/PMEIgDdX/yF5LMkh2Ce452h4D92QZpQaJIspvNii/oFPLMgC2E96B0P4wADM1WPqRm/fB5NxYHLPyWIkzf+/osKglKFLodnsbn/JHlZnO6f2poXoKm5BMm33ht/Nfca/nYQCH3cW+LiJzR1AV/CVuytA07uQONhQRc+2GT72NBxiB3haEOZdM5IOIBBZXUtHm20t+ASWnskyjtNuU2YVVvCWm2Cz8ECF0QxxwItv1I9fW8M9nAZWL2JrQ/VhICr6d5KH82zPfo+t5BaMNTBsxQHykc4cUSwQJYWhnKEqhPm/H9K3g4Usk+sHhuQYzLtfKHJ52BjwQvw=
