apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitoring-ingressgateway-certs
  namespace: istio-system
spec:
  secretName: monitoring-ingressgateway-certs
  issuerRef:
    name: gateways-issuer
    kind: ClusterIssuer
  dnsNames:
    - grafana.kubeflow-jutopia.linecorp.com
    - kiali.kubeflow-jutopia.linecorp.com
    - kubecost.kubeflow-jutopia.linecorp.com
