apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "G9npeO7FufoBZO8WhuZL33uSE4Riy5lIieIhysw/ZdWEOzXB0U0zOlwTT9nyezUG\nawDD+tKaRaQkowOxT4WkOqQAJAY4TVUtP/U3J5BGA5WVg4V/8F91Vjma7XkN7rnv\n4pL7wXg5gcDsC7Q01H4wEVWGiogxl7MZL3J+ODqBmbM="
