kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: keycloak-postgresql
  namespace: auth
  creationTimestamp: null
spec:
  template:
    metadata:
      name: keycloak-postgresql
      namespace: auth
      creationTimestamp: null
    data: null
  encryptedData:
    postgresql-password: AgCG5itHPxjOBtxSrKxPA+zxIyWTcTUZ6fJCXp1TW1Q8HX22mzYfImaE1/r2917cb2WFwMiiRIZPvm5FxzoDoeazudkmxJ3PpP3eKF4P9prE51BGjqiYsDpbjgwN36KCR/cu+ubmcL1oVLyL35L2RnVpuaujWIJ/BJB6AhHFdZiRPnGdJMkqfdpf/NRqo/HfRlbOCExtBcAWJk0wu2mwxVCo8CG6+0rO+iXEDHiMmmpISvpXeL0hy23Qp4i+Gu+q3u7Xkl1kMvRkUKGBr31WIZoA24BLs5YRi9YTyICKolZNXS3kdVwZNixS51PUW9X35tpFR7F4Hj8SrecTdxG1+UwFPrxGf0ujY+0gIIKPV9TBbRf83wUo/qgW7rN5Fe7lg4paTWQtq7p4lzcyLib43vm2/gYRt7VjhPjM3sy84DVlO9/rIPZV4ZAEWswLCdd/ZgBwwIUQEQ3g/QGONKLx2Rekae5uxBVpO3x4yNvWRl/frs+84Ql0R5bSafAUqf/MK6MIYb/7+6eZ3FUaEefVQjkzDAMsi7jpS3S4+mIH0YWlRNfLmDxwXW5xjbU+PCscxADGIPcM1wkCR0Io+Ovm0ASfCv0GIMxTMw8is/paTlFOLEVUjtkVKEb0VRwUQfwrOD9RLqO8NmwtpcBRlbpc/hXb5m2B0HE606uEj/vImxZ8oEa89H9iI41veMqBzruJN3Qobx7H5FIZ8nEK8zRlY1z4tiCJ9iK9hfeErnONZcIEDw==
    postgresql-postgres-password: AgBId/g9dq3M4soPRmu1acFCMEn4lHJe2/xLIMbw/CLDnkhZeDlnr+fI7g9wz9cVrw0Y8qm3LqgS5PukhFk9PaOLBlMXb4jAOFMnrwiSb8y0iJGhVctfQv85Xn8w+kc/1ETkn8hYtp3RjTPYPAa0DyF3ulDwqOozjTlxBbdpHHjUxCI/WpedGd9I23VNeilL3r+2QqIFOfBI1XouUuQV+2bZwtGPV8rreDaNrXG23eIAzaylAOIQ9t5xbXmmywAXjvkbPwVm8yzi01WmbmeXpq8JQmUtX7NSfoUPOjrR+0cD/J2pRT15OdmUctrvtrW2fhBcpROhwGAbFNHT2dJXdx5jdgpXj5OPaqVBxa3OmhgrL+3W+cYKHvQAwZMkuxRW3r0trULv8VCmP0yDM+UA6C0oyYTrFLiMzGDLbRmg/mLSoWtviinAlf8fAzkZ0Puq6Q68NwN9n60qyI/eBCTRZGOtYjSn6b4njLFQQwB/esFX7VyQiy13f60sA1jXne/kzfxTk68Y0qT4knvibRWOWhzFkMvlBeVxmgFnk3uW8TH4a+DCf2jsDcSLKj9UqVJ+/tuwNAenP3LWI3ul1NZGR6ygSKrgiz0xn5BLcKxg2RhK1Uq/BBYEfRBMrEuqWY0j2voxwqxgS6eu4NhKSqTiqEnAVBuSIoBjSwWlrNWE79YD+WQIIO6YyKaa9xiCXu7X0tmwSU/kA+7ngFa2rxljw1R1aYmwB7RCZzPqJ5h5lNZ0Hw==
