kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: keycloak-postgresql
  namespace: auth
  creationTimestamp: null
spec:
  template:
    metadata:
      name: keycloak-postgresql
      namespace: auth
      creationTimestamp: null
    data: null
  encryptedData:
    postgresql-password: AgAlbhPkdAj4S7A+OJAjgzeaXEuqK1cmU2Yp4HTJKLpyZBq6cSy2jXY2tvf03AjbsVqkg54f8cUWKnEZQHTK3cmlZxn5TN92fTrSyIlNEA/97U3aHYojImetIXJ/e2ebQoFWi1hhCcJ7uzYUVdp/I915nD2NEm2aHXNGMH3HbUX7QIWH9qFw7JjleFI26AaFcPnoUF96wlZ/5gXp512P3nL2Bd5nJYP7Mk9Mxl9Kv0iTtkx1bVopT+/x0b/vBDu+8Rlw+6e+gwRTi5RwDkRcPdqifhSKU7tBhxLXfYoenKjzsoBNkGD5NOgn7O70tu0UvrBNaUEAkaOX5k9XVwgVxu3W39I5Lwq36uf+XnZzDhWMp875SmE1rMN21BXn8Bt7HT9mIlmAVX4SuPXi2fuSYIPfIoYjlbQRi3zjPTQxjAMLbBWbYFATygXCYTNeTt9BW18v74Pjwheqz3rdBF/JXBiOJ2+U68K/fbUFzWGRtwn+RBkMHOpFfEWjJIhCqGvkjc7qNsL4UEezaHcsu6OmPFpk+71VgT3amLGWQ1ZL3AMZolgE2ElHIcejC7F8EwRpxDz0DEmm9UbfJMbKFrldW0H26YxdGXl2mxxqZIzeDvCkp+Tx6Kqyx7ZhsEioCE0mgXhAdNepcjQzqIrH5E/HymrdYW7Hp9aSQ5ChD/q3UfIlFoALorw0rOzaaw+v3Sa9d4t8OoF9ssaYM2LitzkK8ueS41vzA5iGEXvdJlSP+V28kw==
    postgresql-postgres-password: AgDJp41Mst3NICHB9r/xVLTYk/DUvf0c3zfVCxfy4jQMRLsXY/qYZAth04CAYvHOhbe9WrG6ZtZDKD5dYIx++n+LbsHMy16FKFtgMtemw9cyXiHpCwEnGexBe98c6EbPsk4/5Kg2p/n5Z6MmDr6/vDrjQd2y3pCr0ONqw9PMgFkv3aTfv6l8Rdh+cy0m0W2h7zX93yF1mAfBa+Vws7o52df9MxncYpZgsuvzKiGRouDAuxfX+gf72665qhMzfHi+Y5cTV/4oxiV2JXRdfsmlw60Ku5WGiv8TwIzY3Fec8ls2yEqDhBmLfK43NwdEFjtsSWSjXFVng5ixyMn7YXhiWhcTz84IXe3Ee3RS5FWb7ZBe+hRb3/2Xo1Hp4qjMARS1sAumC6XtT5JCFGMB19QIjcJDRa6+t8QqK1OaxFsq9JgxypqoKrh8zDUl14zlSoVc/dPzVv+65/buIEPV8I+AjwW9lgu8RMhwxVgVFGCf1QZDN5+s9ElOsleGosTeaW7OAYGB9MrOw/fnYGlShWWL+1N5vGsB6CjJ1Ry8yQEtocWIbkFKKKH9B6N0Ws4KT/mQ6X7HWnyRW+aPHG0aDABjXy/5ZeulLsWW9mw8xm2dFojy01N/RSjP/nRa4aj5iROaB20JhnMixempS//BZyUkQpZfBVlzSUGAQhwta/W5ycE5lXYHPskRbWjufDTT2aJDMAaIrDrWJTEVGbpo38sla7JIFcdiQCs5caqr7MHYFsVSNw==
