kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: keycloak-postgresql
  namespace: auth
  creationTimestamp: null
spec:
  template:
    metadata:
      name: keycloak-postgresql
      namespace: auth
      creationTimestamp: null
    data: null
  encryptedData:
    postgresql-password: AgAVJ5d2CexorZh0DFDWf908TKWb+7OU1NumzsLDHz/9/1PO76TbDrCxYxhBUW6KFsEAhFWMwloTL8xFgkQNuu1/ITGAKbwQjmytwd3Qha+SKmu2NP94kGWpR/Mrc6zgzza6X5S5FT27MqFzBR/yTQIAqgj3WyQnPzj7PCC4p3rSHW2LWSWtOiDPkqoRYaYUtkqncFMfI1Lcg31DPxdNOU1v57/uMpBaaLkt8ZVbkEbxnsXZR5HIr3BvdN7Iuk+uEbNeSdyZW5+duiwXsr32aU14E7UUXDBXlRWn8ksClDQelY92xAXJFComNNYhGLdq+PqnZfBGvadEnh+lZH5mLTZKKpUiwWP0kqStQaSTlnycARiOSexkrsAkWePpHHJYdu0D1ae37W8PDG5Iv8tkeD2D3gAhi3ex4sl/ehJBenxpcUPnW/0im/2/pVFUuVC0ClLlxHrYKKSR1m3H4RaDATQQ9PFID+E/ls86yIs5ZMSkZ6g3QB7euzwR4R7gNaf+GGzyoA1xifNRNveeC25zI0/sDOgYXgwvMyNxAlXAf6NAHQYRe+R6UNP6L8S3LaE78jTor8Jh1flRQ8lFXNv3uqnprvw9bo+4UkI3tp3WvTxUz8nZICf9zhbH9ZdRhxmBMSeV/maq84wK6pwSR7IVSAMTHR68rThaAlmdF63o5iutlg+ua1La8yluoROWBsyZyMn5JlsEdCqc4eBRRqeC+uf6WG4lNyiSp8v/2Dwecy1GoQ==
    postgresql-postgres-password: AgAtFbpQvd1sj0PPYK4rIAtbh51CbuvoLRLZDOKzP1Jxnc8GGx3efqr8vWpS/l5umU9cd+QW9enWo4u9inSkjd4IHBz8Fo1WaHfd/anmWa16WUBT3p5OHiMV1eqvLZz/kL0hEiq9aN1emctSSuMTPgyAj8xgz0F3iXIqiRuUpUP6n7LTksdfpl1uhvqXcl6lLW9sGr5wEJ3oDK0LaqWRaI2j5VOJ+EUyuehSgf+scLAMeZaCv+bmdtxPHO8Q2VPuu2GDT0vdSpCeUJefVuqLmshChR9ugGbKJuuLdwzWB/NSTjPt4A3igeBDnzVSiGXF3LYnJyKy5SpKn+3WgCjLkUTpCxrQratU2Tz012NXaD5Pe6eX2sYMeF4Yk0oKwPDrY+G8MDTcjtelUuOglAPHt1czdBwd14q21rfJWJo3b0Q4gjpd+r8FbEg/wC2FcYK/66RxkXqgbgnMgUuxvEhD0WzPTcQOTIkCee1ovuhqajHHSTWcmPutOPppx1JmxwITqAKOqh4rJ8P5wXAHvfkPZRmlVK4HBAMUCb0lqa7q0SpjU0pimZvGGeGW66gh4qmVx7cwTbkmBJGJXokBIpmJQ4eC1IuAj4Un/AyH35d60rxgDoE6ndmKjDJ6zseEw9nwV+LgsvWpT2saVIYIuKPIBJfsxIydUTNXcdlkIxUJQkFrhniAFStxJfedLM7ZeeRH81138MHZ/JD1TgOWnh2gtSICnHgAs9wF3eMIo0wMg+q58g==
