kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: keycloak-postgresql
  namespace: auth
  creationTimestamp: null
spec:
  template:
    metadata:
      name: keycloak-postgresql
      namespace: auth
      creationTimestamp: null
    data: null
  encryptedData:
    postgresql-password: AgCYVvUOWX4PTUU0VV5RaDY5Na16cQmrWbjDm71+Jp7gVKOPZIqDmYayj5QI81UiWfyKrxsjI8aBsYcqdvaMRfdWXsdavlziyJBeMMituDBrmPJq593tUfexmWtoxYnYukhZ/dr4hS8ovstCirAOeeuimXkyc1uYcbX31WN0BwgQYhlEnO7jY1udtC6ek2dzYtM7Xq05zl52U+FbOQ6SYrIcjHh/cYhhurI5fuorIrCqnXLFWOSyqlbFpq//tTrg9a8AmlwtZiEek1UPupo6y2RcveRUNYz+XPli6jYO9y1IzGpYxWoGQdSG6/nCTWoI4WCwlQXlKd6muYMA0kWPnPk4IMKULtqqevvYxjCIQSVu8DkYUP3m7HMZh9IrLIbRf6GPez47tvYvSO75bCIkbCWLsMBGK5+UFvR1bXza5hOV3ZEqCAAXiHrMfrhxLlaNzrhdBJD35f3PHZ7MYOdjtvvBPh97lvPOgM/Hxs87ghKzFw/5iscFm3gYM3VWnQeW04dw1aIQeNrqJY5RuQgxc/kVOJDTDXSWrPxuAdULfExs6VcpmRda37Vh6RMg38XMkfZVvjzCa/f2kh9iz5U4kGBQeXbk8y5LOJPr8H4PmBFeDAQk/F/p+IRU/qiskO7TG0JkW6zSGlVjw0vXd95a/wDJHeg+Qp+58dXjTAb6r2MlGHz9WCc6iNNrXEv3NjBVpLJPIkFW5ScMhGT7RPu1eRx5puMZVg7+q5mlWzKrB2l6pg==
    postgresql-postgres-password: AgAcKS1FQAmKHia96Qqf4oX9cKL3XbFEFpQI8EBag+9Lu+rXaYIyyr7EKrOpS4wzruicPs+lxxn/ZbgdcoG21to1i81m3CzcydrdET5jxoUF6Hg9dL+VBVC543Mz4a9bRTMsR+u3/cIUf/jyVDV0G4xVwbkKTh/xa9fR4OkJ3p5m+yQb07rVvTzoK5XhCk5ZoStcgLF5gfKLEw8wZChLOMw+CVu9kCWh2fkNAK/nikK3Xw4Q0imfKbU+TL3Q1Mk8tsOCL+0jBM6To6hi5dP/IfQ6Ze39FpJBhtfhTI/kqGELconEpmtandC4yZl2YszOgZqD5v51KJEScFitf9/slCtk/EHL54ez7SsCuTXkxnsQoHTRdO784lWVsvZuNBsJAcQesn8HUY3Wh+5yEzdp0OWJd8TyJVJswdaC1gt8XJc3J9cozrrA6w7a8GpmVjkbtlzmGTcd1DhdTmkoUQLtHhkDjoc6YryUNhiecEQO2Ecl7Us1T69ts4ppswGLNIMIWWDphXZiDcpDKDW3zmbhTSI9Aau8zRx3UkDtjvpuls1wEgr3oubC1/ETH0Ycf5oAqbmZAnbZocmpo9okRAM7oVX8wr7Dpj1daQbj32iVEI6AzxeR4VyYzqSKlHufzmX709DQo853LewZiyvIOf8pi57mEBDT/aGzayWDbIQ/5cBO8UffPLYGlf9KATDAxh91udfi9EeoEb73cXqCNwhmAhTkLZNLefjyC+VTqfzLZx8szw==
