kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: keycloak-postgresql
  namespace: auth
  creationTimestamp: null
spec:
  template:
    metadata:
      name: keycloak-postgresql
      namespace: auth
      creationTimestamp: null
    data: null
  encryptedData:
    postgresql-password: AgCM+ie4toniYla2gL4XkS/zpESdqPCCiWk7K3+mlTQbxGeEGDzI15CKDUoWBZoZnKTJ4XR0GFJ2XWZl432K9XDB5Ic0dPuv6hbcqf6KZZbY6sNeIsZ+C34V/PYnFZU8DqEvoHu6or2goEpIoudAiDmdc7rA/9ToycqQ9oMhQKkUC0mi2EX2It4BjSw1+a7GGFz9YFn3+NCT9JcRHLPDQIQfoQwaYyBrS7HYinWuZjBCfbRHSqQ5Piva44cyY/MVL+lV7GUW7X0CRgZWxerVLbO2Ej2LsSpKFLsCV6JLD+MCOuRHGs+ld5L+EMUgWEUkAFpGJisTRE3p4ZUA8vEsRnvxpzh+rxIZgzmsuROjB53TgeCFFTm391OmsaN64SwvMrgTSmDAXQpFrU7T2uCuSfDkMQ0MgqF/VoS/vT/uhZUFiAHg/ytFTaaS2f5kOmS6sQ3xIHC5lWSb2sWkqmJcqu0b3F1Z4PB8aqeWESS0MBKHThTFLwZzmeweSsp0/Ctt6wqAymrCpfwma0ojvwp64jioaeSaxU+jUvkmReZcc1HLQ5rM4Gle+3gWs0UERpmFgFwc+hAxv8O5+lc9vXvvBuudvvAsMdnjCy1Oiypdb2ds4VZw0xm6Su5RoF6agShrsSe41yX5dt/7Rtd4K9pOReJncj8v0wBgYmnnaMg9kaCrr7o6IBUPGrb/jY+ggOh+cH+rdTreoE80x6jz5oMbJEP51oYVT8vGDkSImg2LK3HMfQ==
    postgresql-postgres-password: AgCbvPUu11xI4YDu1AouIJt+DWRKF1OHD11AJVO/1Dffg8PeWnRGwWriWLmeqqgiRLjzvqJ7FnLp2OOhsGvP4hLJf22bOpdX+ICuD/+IGHVCDR5Ur46dl6hJ+qO8wnnMTIm687KHdDfL9jRUmt7I9sUXxSbRC2OBTocsuDcTzxUwOv/66McGjFTy55MGaFrc1Ks3jH4OVlNRoFH9FrYhsYPk0d8V+B69XnuTURIgrkKglIzUViM71bxuSPUSBxCFwYNghXSBBu8kT6/MdNadHAi9HpK3zY5UNvcfP5jqrv4IBHLncWNU9nEGHYoyIKh1/cNCNyVBZxQ5Zq/plQ8x6I9E3xr8sA6f/kbJYnbHLvNZ1EI2tAeyGNCG5cPDZwyJs14tC3l1a/GXsG8PJluR/fCU5O+nOxDpa1/7cjZuHhPK+G8QmA4VFlois8rTsSWKBAMZIKVWiEiIP87DR8swj2Nf9KLMI93RLCCqe2OXGbZusgnssudKI+L2Dz2V6iJT26n2LPPyduzJOPwUk9zEcGzlblCb1QfmCZq7ZNfHWMBOsCLWQ9AFyVarIb7AfmiaE/KRe8HEaBe+1i0KJtiiPKNZrFbXV8fZ+U4cPnFBvK4kpAh97Rw56Rkm04mpQWg0tDJu15+gq4RTpLD0JVt7pTjSGZEWkmG+MmGJnp1YjwiewMZnvY/I1eIWEzsGz9qpcGISN1N99hsLUHcocFVlPrBuwpFp1GZ4NvvzIr0A4D61yw==
