kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: keycloak-postgresql
  namespace: auth
  creationTimestamp: null
spec:
  template:
    metadata:
      name: keycloak-postgresql
      namespace: auth
      creationTimestamp: null
    data: null
  encryptedData:
    postgresql-password: AgBIjeHfNihtgw2X0xlwUaZUXHqnxIys30m2OfMxH5ld5IOuQosCMpgsNkSLJpvMF4emSRyUCj2QHbhThLLVmb0/+hbXR2PYzCNe8vleoycDUS+hBCJ8Zgnaz/ODyiM2hNB4kE7Rh5oofB1HZrDUocZm70GMMNbTZ+i4imXHzcM9nHagfv85RWf+anYOdP2cpnLHMTK6sBxVwTT1u7CbdvZ6zw4boYME9hNsECEHEsNBkwOU2I6pYarPKOj9aazyua1eRQrrrRFdivxj4plTaFj7gzYH/GRdCY+Lmghqh/kXwD9kaw6MGU9P4RwAo8zv1uyW/ZRd5Ce+TsZrNaUQHf64NhHoBv+I4NJNzMWpqcSzy/+a15Sazv+Kz99/CZIw1Ms2kahegdq4QCGC8zQeb3epevtUGxuFQYurK3/m8ZllPTIE8bgtIMS64Q2vmhvxImeoqvAtaFsb7rlXjjHloBzw2Wu3tpO6qO7PSTan1NeAtQiYoni0Z6W5vwGadcLduHCL14Cvx42J3uRcuqir1LfYcd82YHA6hRroueDUhljjVwOc5mkC89YqTDp9tgYrkAtmKKqmW3EA3NC7EVWPoZJXYHWrF6jRJVuytii2P1qOwrb4b0U4yLAsS0GByT1esmVeevGafAopLemnF+FemeZZ0oRio/TJPH5CPqo5Y/o3uFV3Ob9CRLnSxbvCY2KRtmBdqhInPWCQz5UU+fhQZDJmBs1ExwXdZZU4AU7AlW4CbA==
    postgresql-postgres-password: AgAvM0G/lmmQfVdsiUw2euCEGByW7DyalWDJK3iyndah1ZPqZhjn7U/5qVRR+DAVVz7BNoCa7yetAmnLSNycht+oWiEOpRhjPiSrc2+4WAfidub7c88frvKozHy17VA4I5KYNjJ9GzZV8p4jjI5wo+EcoBuJc20Y3N+ncpoQ9JPONcoQKcSsOOUhK77FbZarF4Tt5Ai8D2YQgeixIwUFMhr2F4bgVr5HsLgaQd4+DUwqjCf0fPgOqOXe9UnsaqVg7308p7d3dGBjxDX48vtqe2trk5Aj1YqfqhMbfa0N/Oy+n3C0+iRkYWnda1WUVi6bFmJ3N2PzYZZjR/Hbk85EDxpe8Bo0sbFIg2oueeRE/CIX4gh8KMawwuJIMGm+vyy+HN5xRM7S6cHJnyEAsudj993XtWKGLczOxsjnnQ5Nc/zgQZrqLPOiLVC+XpNw5XEhdUpyvzL/M8+36n0M6ubQQmwQVjV0D/VfeZePlmVS+ERuY2vfm/DVWrK53QUfdj0EBgLG2AnBPhVs3U1uhm97Fb1nI6cU+OlOXMqDJCGuiKMaKkh3kLDx/+EGnCX1dUaNHfakvJtALAm5uXtA15gHyN3FuP6jqVU7AqdQcXvgAYF5OMW/IIDi0h3UMk/4lzjdzIzqsT0jDbTBQ369WOtGte8XflvG7tDGkHpICrIW7CT9hzAIGgn8bWSk+kD8sR+thxzoHNObqr5GhPlh4VBJH88LqG8VxAiVRRK/kOCZtFhPLQ==
