kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgCabjaJNqXXlPGBMgbBaRib/ONP4El0AL4IBQezCsx2rv0o4IDEcl8dszXtqyCxmLKeKuUpbe84otQj8KJs/M5r7zPZ865oaqpOF6liO5ZjzuYI5RkDypQnCysTnMg17uikWCyrTrtrLTpUzd6nTqvR9qi72clMddiGDEmtMaujUYJAjxMDAKHPxpFBj6v4+4ZZkJKJNc6kapycFvLq/h1hJXwIOtY9bFx8oOD30fx9JLU7FaxYeldC8mvgF7EOlggjSZwqShPE0pwPRbcPRr71HdfbADFrsB02a5SEfKxGoMePxsEIiqNSPqHDnyCWc8sDxwLPlnlv6y6KsrlBa/MPWSHJPh0clqJ15+Hqoi+xWLjfnIfFldbpP9qH1ra0++aynKbQEYE8sfXEZ7ekFqr14yQIYLH0wa9oEGRkBe4dckrJXfmR2slyvxh2IB1WsrTZ7mB9a6wa9T+HUAfXfI+uEo+Oe4VQNYYsWeXTODWQvfsarxmYLpXubncj7ce4Ra/W6ErAdCmKXUaXP/Nbpp2gweBwhaAz1UgS5st6X3NttKV8J6vIHxY6hiZzHg3MfD1VCD34HDpGzu/WvQMjARC2W/FV6KDsQXSa3iQHqcsn3mwVHQ9CJ3VuUqb1QmUDt/MJ7NnRIL00n2SPRQpI6A1etsNzhy605vIGZBXVCp9/SFc9I+AHUzwSMLojrOcSmwd2/kyB
    admin-user: AgADI9DCGlflmvUKGKvkrecUExRnBY6vhEgHD9TBdtxk0TqTBEtvWU3pGYOcHDTMORGy9bwRMlRU7vdSC1dVuTyt6HGQz00GzkVPLT2KwMTshhLrsIib8xF4XGI8BjGW43QIkjYwingHw9vB7iXUBr+iGMIr9DCBg6pR3SHW3CCR5lTErzOyO7zIvwEXAgm5JEAAlh5ZALej1njLqwv6osp4Nrwfa99MtGIO0IuMmZLcObli7VZ/0zOZ/3FblSfd7BhLHanC3UWqIKzGqMcc6ZdjeM8tfbfp+sB92xiYrgpo7wjlP353xk0hjeyH8vr2tIsDFHEsrW7XMNvFavHgLfgBS4RMl+VqlPXVrkYgSgDjSa5OFryHvE6vgvtmia3jjJzgGjuAynXKJJ6z+5UuhF2rZz8aa8x25p/mENVyHVEjR2i1tKBw3DelVrZWhyLTYDR/9dvKGPHka+9+/FmqrBvJBXjXoU0IhRFKvgo9wrIpZLA+937QWiENlDm+StUfVF3GeD9OU4L+fX+GOQKFp3++38auN6fgSMnxRkwBnfWfyQW7FNmJbok1zUQrCNuFttVfaq8oCAV1i2229w0sMCHzm9Fp3cAbtlfnemWUN/7ZVUcV6M+2tZEF09qpM+NHNp135M4gY7zLw4quXIoC/RiwWk1N8LKOXOZrKHuiGZuExMhixRlPEq3guFNlUUruVlKhvvEbFA==
