kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgC5VG3oOH1dLq48Gv0OEMedNCbmlx7U85pwOFzMAvifN8cpFRfgSLkvzNCCc0xhjOj6K6A046+riqqDSNmzd8ccTPjjD78/onDrfi6eeXTPtXA5AjXw3gNX//PajqGxsL3ZFeT7QF3ddQZMEEjkmRXKlzRRdTEIqXC7kl65/ljHLGXRAKSi2cRPRf7m0jHbu0XoFRSTRXe5Cl1zp36OjN4npifNu8zrwCENa015D4/R4Rvc+YOf0+7Z0aLnoYZLq1mxgNXCVdGFtY/a0d71zEcHwfeGtJImzU5aWJKu63lQfyEJe0nClDd7RMMnsujR+CRk2aIf4UVgl51QVLFbtVTlIVriRnhTK7F9Uc81lCfBy9EvqkfQjxvmbT717R+rxMZEQmSyXfJMuGoTybowomQYpC1/gShTtPTVKOAmRatnX+pKSXyiisnP3CV2zgm4ZzJHp+XYip8U6xUX7nhjLqF2KHC4x8gW+8WAVW5SW1E2BqUtZPPKs4X3Y3jWj9Xpf3gD5YcCnFE7V6qtgDVyuh42UjaJStSd0e6NktqDtgkm0emGut3KP1KjEvbgxwrG0U33Y3aP8yzDTR1EoCJ1zw9daEJ+XpW3HF0M6N+k/esxPfIzkZHy5ODkpvbaLBEDOuoh2zMy8b5Jz9G2lu1Bga9mW2OFgLlw55PXMjtzW1Olr0G3dbH8Frckin3nAXK08yQleX5q
    admin-user: AgARD0x2c2is0tbTZBaPhHUZH377KpEHVmCWuKws8Bz8ps7bZgcbQZNWNb4+aSW9z+4HgbSJSTrH/taodFuk7OhuIb3ZazGj3U5wb1cabkR29ncTFHqkYiS4thF5dH5EbQ54hU5RORwz46XkIIWIfT07DdaVfkVlEJH9is6dcXgI+Fqsme2dBjCLY2+hgIT4nm/HpGpa50AZ1v6WRxePCVPF3aR126ZAFndT8J6soml9EQsJDtFMioG2mbBql0W0MQVPIeqCu/lJ5Mnigmo1dQ+DvmEpD8htyvtZhl3rprV6ecamSqsf9b9ig7Y3f86XKeYPaPFFAaVsyLQFakHrIrZTWE3OF6IPf/BF8uy4PJitjdK1BCFsA19oX0NCR/H5gNL5NCrGEo++YUJiq6+f/bk5/23kV807QoNFUCBcC+VWnAwU9VgYTnAls74GHZ2oa9ynrxza35yElTCBbfOUWYUobMb0OZJm4v/AbdAAKMBpgGD7eOa5cmowAVHDYmA9c+1qc+Xmb9jwdG+vlOCcHkv6DTixYCHG4gw5PDEYsTNjJ7Ne+sEs5hFaVZPYOkO9kgHj6xc9yadiNKUMw7dW9dpAlmQEjlRvJ3lrWYDk72kfllfs3dgrr/XIjPhRVzJzqDfRIPdErD0/53mpFFQ6yGTUA2vWC9+8SR0TyI28ZBxWQ/jw9bL/CfcKygdTbgPxw62zFFcWUA==
