kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgAMpH0F+Vc4PsXWhiHXZUkxJK3lbORI4jBsd/sY2gloXIGLK4nX1o8OAYdYoVOOLf8g2JjbcB+y4rrPqZV1lcxdgu/Am3raW3oDXgEM3cQ57KtyRfA+Flx0Q1E8XVmLNdDp3t9REw0szidnBkCTLE5frnosKvNGFpi6sXDdXzPdB6R8YXD/43hZ0NJXwMxngtbiywA6wGMTOf1m3mG/izCVh6WEpTMwtM6OWRumiqm9dxXeQws+Hdf1NCM24gAol3cEVkydUuJEn1Lx9PS8BquTMJHl8P3gxE/lWFok8Oba8F7K7kRBOt0w50T3GG56bwNHCgjMycjWkSlTmCwBep9GTSmPT4RjD69tfkYcUrdoAp/17c3lXz5uOzPZKCf7U+lni2cDHRcQALW9nxr+pqvQP/Dq6AahGgC6X/PmTqqh0PWnEmW8fsUHRSGUJdt/ivtuSi1+DRIWJDcjFZuPeIYFnhjHg/WQ+TKPrl3jYSVJ3syrXjq9tcHRgsyty24IN1YfwkddVtP/YLkRdXyL0g9fvVePDXGxg3uIa/+irGZsgkbCPhViCbakvDXq4fuHqu25lEqpRbKAKI5jTIU2Tjn0QzGzVtnvgyh11ggH0HmLUIyap0OrHhfdHbJsdC1bhQAo+Z6bT33xcmU/YWKeyk6HmLX2eZNDrKQbScgt15t1WtbmZe3SXm1ZfVF2wHSNmy7/Of2b
    admin-user: AgB4MXrXWi4kZh9bekkbJQb+NgJyMtc2WpOuhNheeQ7oTWxf2fJZOsTkUJbBINRIsy9Rcf+lPJcZHvVyOLu4daJxQBkUChSnqLKwnIomnoIn2PuS1PHpbUUUQGrAC9EGwypCnA+6NRwHcL5TIA5bTfxWjQ+iNeHjYGtODUGOniphKK3jc5VdWZ7qG079UzOnvfvK6W2UZPT/gxinDPi58PaKlEfhKofWgwu2vIGpCY1pWLacVuSi0Xjx7yH3DhNfvazZ1NP2c/V4CCNwa34v43iAbxkKz0RMvWq2xAMWqWAfGYX3vj3feO2XKijm1UIA7bN+GjzJC9jr9EsBOYrB4n8/DsHZMF9AYmo30B0+BymTeldUC8sy6wW4jlrP8cD+EyvZejqYJCYdVD+cXGkBHD1EMnz4imjSZC7wczvoo02NN860SodEzj9rCFIoYlCo3lf6qERzwxlpf+T6C3nJRw60aCJV3b5WsQavt13D7/JcPc3aFk+VYNSJcKSnWsvmRTRKeZLFl04otMJ9VY1Q+H6NU49u1pdEwlWN5oaipVBBbNUEVYL9CAwChuiv5l3PEPXx1FA1YJ0HuFS6jozRoz0WSC8GonGwGusw3xKpsqhclSUl6+eHU0zoORE70PEsuc+ukzUX+sbMeTEjriVAZDIVj7T/3ovTqUnoNCynU43clYgfojrJlq4jxJCovIq8oX60fUorEg==
