kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgAIefkz4hQ2tAQxTVYY/pM+2tNhL8qBg9YQrdnv7wao5BmaOwhrNJS/Iwz4Vvy2f7VeH1Sgr//E90M2dTRm5uMjWaM4++SJHz22yy/8oFm3LaxZIetau36xLGvcB7m1WgGA84OWt9ELvDhkzDc9pT+Lvx/EnC4+Kwx5uxUj/0mMgt+DF3oBSjBMR9Leo6MWbPzxnZLaSjFP4osYtCrriy1Z6xSGEFqQknWTW+EjT3qyMdXIODfw6V5dXKYQsYzr9Iay+gGbDXEw9gP9gUcAXplSNj47FnC2DmR1x3KyVdg/GUhhhGx7lZNea/zOk8FSG1nTNE2e+PAJ/OiXPoxN/ny/oo28yRF4kzfF6A/lH4hrkRuhZnThrqD7oE/U2fT+WkDV5nVvnaocpuDE3ZJv15jJsRYUd1Uj71rkpTKbX5/FvAwVfvVxEShN663wi2a1Y45GJ62dKlsFZ/Ob9AiE2ZaX+3g6XeXUzMs8OCLQY9lfCUtRYYU0bIZWxhq49uRPgqDW8vHC+u6Uhbf6SqQMqquGLS12tc2KM9vfUQWkLuiG4MPeuS8Or7N307ygKTkdb6zxqriw1WNlrn+zbRPeTAv1DHM8LdqTeM6U8OwtWTqHCbGge5eyIAGflz8QhuaVNsLqRHA+NCc+s6xVntlS/Pf3tHnJodgjioQ/aj9W4jPQ9GM1zdAzRLCe5h8rosa7z8j/X2Il
    admin-user: AgBWWlgyFdz2zh82t6Ym8ENA5BvNM6arxbYbcZcEusFAiNKzJCrNY8cN9G++Hn+LOL1/JFiEhWl4kqzRfIng2e3IDs+7Ve9tGpX/3CKeliXXZW7tJQiExZyc+q3D/bP/fhoI5nk8Z0493J0CJCKEevO/nYDzJSqHF8xkEyLeUftT7oON/f+U1E3Y+E6obV+VstcYkfOZURvHDLw5Kdb06VF1hgrdK6UUZkWIzAcAQx0t2L7voZeaEtH94+fNmn6/cBJ5k+Cux9HT/99asmldF2sf0wGN7MVbH8y5xGPOL36SdVtEamA6uZkpiSz4KXWw9tsN9EvEWcgDAN3zeP6b0mpOHPLIWiBMYpVDvX5q9PAfkzVtOfKIP9/e1XlpZtQuafQfm7GedTLigtdT0dl2OmrrW2DqQnX/KjEoJaquD6BhqJem7+rF60doiD4VsHNO5Sk5xP0sphu3jozNnMWfVHU/MqslJY+p31o3PLFw+4OMGEGWp2O8eV1TptSHORHampntOU/74WfECHROA+GcT/euDAGpPYTWryeaE3Cq4bNMyyoHyWS3fEftxxQENyStYlgLzs+1y+iyc5mZl/Y98cVea9loQK2PtONGE/tsivwlynCjiM16ara5LeLTgiYFeXjsrIvimXwV6nX6Ice+fz+ZX73iC+o5lDiO91BEfYEo8PoKVOP2SlA/A4q/hiG0tSFNp4Q9Ug==
