kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgCDFUoOIlZv4Xc5CQJNjeh/zaSi3wlEuGCFD4aT5mJAoAqyPrF+cXy92Nfjwchvr6FW514nkNBrYs4Puii1VBXngY/OZHGJeeLC0pPB08Cpy67mkEIue6AJi8rhMB2WsmRVxpQgwyYRjf0quTvrhrC7PQ7jRrpwmTZoVUrhgSUMwwGfvKnUcbd0k+FQPID1Z4o8VIVVNHE6QbEbwmDEsNH7O1EZs/1+9ADkABO8q/NesEfeON6x4k4anc4yvcgGh2bYh1nmA0i257cvfeGEa8Q6qVSHCqiMlhFiKjl/qMbgQHpAypECbFBehP17xwM8p6NwP9TdhJl/xivQpdGwaPBPtZbpOaVB4FBX/1kys4mUTLHrv4RX+4dxsySaECNnn4pvZhIYkY4rGa4vKwWr1R7aqTqB1jAhh97jfVt6dwOsjwuBI+VlgZzETLo0i19fJ0x4Tclr822mHp7VTVl9dsI3bbYtu801LWOyisoM2lxgnaS/qzyN7mk3uorqArNWHKwsS0iQf/TxU5kg/f4zNfuZmBOgs5Z33jvwv+Lc3FyFaWQN5h0pJ9K9MRwyMIK+GmyoGao8yS12BfwvIdQDk6+O21CZGuVveLaOYIYoQ9Wtkam0kq9b1BsLl9w9bq13zP0XtYH+IdV6W9Y/2mKmaalrRy0V3tmd2Az1nDG6YXcPRF/BCRMrpTWSs7Bn0iMcT7EZgTH2
    admin-user: AgBS0rtD/doz2m/nbtghgTWqvocIrsd0gDKrRVzEgOEnADNRd+buSZoPrJlZz/JEr3Yt2rvLtWJbPow21NZllMopHzFGdVlOlESSEkz0yRLS4NuPR1lJYPne/jR+fXdWd6iDFpCSa1M2sL7Eo1msBPT0c3zjz0tqYdznELgfPbcmgWGOEwTE3BGZSm0OWKHrjBNjsfGKGD3JsZ15mhklcDMBpQRcSVtSoh7i8XKeaa+ytC1L+LqCGFf6P0CmVZzZbUFJAErW9Bmrfn7FX56QruWjqeR7I0DcjP9Ii3YYSDG9p2v4adx4j0d+W6qUZnVPApWEnNIeTbRlDWPRIN+YwIuE/2zR1TidDyVSezI6VTgd3s7nLJ0+9TioLJCFeESwUshoPGNNC0d8VbXdcV4qFjnVdpfnUTmVf46z2y5JODS03JeyYNDo1DiEJwjmYR1uB8kutfh0cxsPXKvZ7LgNMPs+nly6kGdNtwO+GDgOgEwI6PmmfziCYt05obvUc+vCP8wXh+6GwQq47TKcu4wRBqpsa8WX+LG7mpC1GkvFQLx+SwQzaY9sTJc3FYJyBsM2WKNAvzT7zedu18vyt7Jd3CDs66zay1ET/aK5rQYZGwb6x0xPPzvXFcZdFNPM9T6uZqjQ8d4zQD0hJCEXSi9UVPwS/UQLC1tpVRbtbDrLg8+akeuT0QRVc1X9VS3Vd6UQky7p0ZEwPQ==
