kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgCst/2uyEv0n875/rRdDZMVl3N5Z5hSsQMDlBDKbuLbH7adSsvyHqayAzXjD8X2HUZxZBs9cuAUepR9Yto9rghtK6c9Zz60RrxOwZPH1ZUaDpAdoKkTmW089kNCoTNTFniEwBWtBr/pBFyoRU0I++hYL7+37aqD/KqEC9MKtcp6gSl1cv9cjH497glfl/E/ds61bvbWLMsPQxxfOOs+UN/JSkpZCpIa92rG+242/3OIDFrU7MKZasBFN7sTnCUP7Pycjte0qn91zb8/NcEWSTaCfCADHJRX1feL6b6pq1p/yq2Oge+9nZHD/Khn9k5S9ka9fsc49Fyke3TmGZsn7gAd+QqH1RLlk4ag7KEn7/MES41c2+PT5y/RAU1SfwAJnDHyIuUbabM6NeNTwb7ZRkRpOdhWTGA5QTxoAkW3cX9hBCN1tmYRpYgOAwjIbpEkULpWX79GZ3tGDPDjlsp49SiZT+6Zblvh+VM7SQ/QabB87VNzyvxkeHiTZLyv5aYMl0vn2kH0LHGzTfZo6V89dj+yMCLKrDSbSG7psJ6opFIIbDmGZyZ0gnIJyqFraEAbQR1BUIbvJtQ2YoywDHqk0FsMhOVf+DJNqIZSn2tGiaxwwtdxPzHq5UK/ZOTeASihnXoxhMeax3x+N/Vt/3RIKpr/jewJWsP6+AQ8t4VDaSQ6oHtajQz27Kw1Zd3C+JI+v9VYIseU
    admin-user: AgBXmaDv/HlMfIyxesw/OezJvORCKtQQ6dowCJtXb15HyAUoNYYA/wQQV8bEvf6SCcIL3y0H+s6QUjtSP//kZxocN8tX/APyKkA+ArC9XwAP519XDSHotaknCkgY2wUtY/khvHRy4H0T+sdF2vOJkZeDU1sM42msnwed2X8+lk3HFPrdgU31h7pqvc0ghk8Z+tImYBgH3KocT6K1gor21cZa+9eU0gtGU6jGuB4nEoyZOgZl5BTiCLS/koUIUJjvZJMIblBqQnUAX/yhVs+aXkB2wHGxsIZ+7DJVXvRdm1wV5zej7AtdD+b9UdNMHTA0MOUd/4B/awGoWntRahcf+lzrHtzFqfVknj/1s8+uwZuqmgJLiF3fRIWUv5UXRN/Crfc1QnYBjnGmP5rmXzMKzOCO7Bx4iSe5nhgFqNnCDCUY0pT9IN0d1Uka7giPj/WjCwATZdyul7pF4RSESSkJ480/JziWD1DwK2Lsvn6N3DJ4+lIHquCeDUyW2s7v+CFOhSJJ8WOxQiKNqzaGL5L7tsDwrrfNChfsQVAvMwYlJ0LvmeUigcxwAk1bjUDV2ougUq83VK2mH862R6X5STOz0qsjy+JLlr2kZbdEJ0fx1wezIS+rRevJFKAl/7EtA5ZJ38MWx126kmxTtT7kmjUlf+Y67EWFgckVxST+tBVmm+6BZVrqiRrFiDB3uOoIotRygWgiLoi2zQ==
