kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgBcTuqf7UlU5UJriyZ9b0PbFjFZTDr+qHbljdCF0u8MIzfaA8YOGN5dW5G2p1RcdfpXcF04VwHbCFrhhSHSLtSLmHHesdv2DKO+nfPQc46Pkbj1P2KnAPN/SBO+DwVUYt5rGxUGMYEKi2VfSsrrjlCgqLV7Dew/ELjRPZo/TexaFb2P2JVDB08dK/GM/Vo8cS0HBQHC+i6R6y82uhWe75VOZhO+f0FjYKc9uLZLaKudUmw3mu56+pOJVxSNyyXbHKjM4/3L5UVQChAV5SAxyEfIvIoTGrkuiwzXU4Zi2tVN2PMJa5EruyOHR/o40KwBVE279SCgCG+6tVlR8TkXZ5S0OBO8oImYSYDZkX6xwMETyWbqE4irPIG15S3hrWl56JuryNyR4p1FlND5qOyinhG8R/+84e1k01ZLrUinmRW253YbyjAZEP8yKqAHWBogS0H2P0ccY6841zCmfztfGiQISUwsAE7akLhHESzu5jJt+8jK2iJmc+FxkHuNhQnQQmz1APYvXp+7cS6OQOdt45BPKZftDEjW+BIvhTb+VYz90gsh7nOF0v45SXXr0kcH7m1ATofDoWjsfCMm3iyNwVfVqbOWl6igTXiw3lhroRrfmLUqpUFSqh8LBYV97a14WrEbOUcnGVZVwyX0XUyMb8rNNac2erjDulnwsFrTJSyc4hGq2rBW51x9s+v7miC5hXVowvwq
    admin-user: AgAQYJmLsKJFPytF5SqbMD5UTGfOJQpBt5LAACUASt/h6z0enQ6DCKcH+D+u4NUjPDkm+PjQzss20DemyJ84lRrA2L4A73dWJu8d3ixHJFoMBnJ8f/5r8adI2zTUNfAmZuHMK+Yn0OX+B7G48sAX2CiJ6WJ7zC4D4cki2+08kGF+D/gQ534UFxukXegR384DTawjQ6iBAw2t19Fte2GzxyTta66OB2EIa/GyoJlzB2hG0Lxbwen69lq7q09ApxXY8mVPpDiaGveng60One0/2jY8Oq28qZPH+HmK0ayC4tC5Wwca1L7ND008Q08M6KcCzpN5fOaaHXNxnJOAnpIz91Nm9J4X6OgMJgsCanYL5sqVF9cmSAgrcrnd+qF2a/DTcQFbwkpLy3jwYmxaMhI/OCUR/sHfEAsfk9G9h4ve1fjcE9jaB8AoY7krEussxPo9/jnFwTYVe85TNNEsq9VIny+HVVVMvI8JS+KJS89mtkhD5fFhKUkkyrLCkk9YvaZpEyLc2reYf5Wu0gDAY3wj+CKgWkCncuMosW0YjPov2RduVSEAok8ezUR0S0wuze9O3nX0V1+3FrBMRMYMXBYY+7n7HAkp3JtMxZ/rduNNp3aNkbWninKz2AxeF4ZJXKbhkptfDJGwHPRMlpGSHpoFimfAuAb4KI4IAOL7M0EhsppIYcHsc3QoLXnSOKOPdcJ7SFBfsMdkKg==
