kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgA3EMVJ9luIR/7u1ZdkntP2xhELdI5pQDTD/c6Gp1Oj2W8XMkZE77hu0pXrapxYjq1Pm3GNgVacrJgU/8lZgicThPoTRSda1GvfaFhq4R8o+R8rjmWiltdbFgwswf2ZRWgm9sq5/s1/1OXn9f5hXLkrQRw6UOpCXRvCneO3ci54E4kaf5slGsKlz3KkLKo2XCChMo4QMiuYHStaEBpjoSdoEkOfUEN30waJAl1dpIM0l48DahIVyl4lWAyA+WwauUNMqCHX8K/r8QwWENGOTOkfj2Q0Q+5ULxXP4Qo8xZ/aK6i7shTuS5b3I6ilaqmEinDN2t1O3VuYZc7MxuPeKCgIkXwYVA+lcpFM/lZMjGl1Bk2A6T7OcoXaYc5nHINc2AywY9hWdH4cPf46ZBdiz8emwoeEZUoE4hY9XFDMpuWKt5KdFwtqGy3QFtrq1dfogk+dR60lHaUupTxRx7Pqdi+odVahrcPaCK1+B3K7YnRlhx3tA5A55tCHErr6kUeKdu7lS4w4JysmBqBkv/eDOKvzmjIOIAALSPyVxPquKZMT5bK25oydub0NDbxZEa8BYLUJ7gDKWGK6J6gkje0YHlinBwjtFTSXOUc+heqXCoAn2x7kxLiMNOxlkonrVV9VUCJEaUpHgP3vw0iNr9Q+QgFC03W81JLt0xkSZlOCRVwiamt0Yf92w5QK6sxDBZ580GkDrr1F
    admin-user: AgBOihVppkoz9l+JTperjvM0kcLxh+KMFjzL9GqYWvPMxYwHgXcmC7zUEvi3hkWCvmThQ91tuKfBjRUzYDwYMqPtBIPrd6oofgbLkZY86rSfUUSmKdxezbZsz9XxEWJpcI5JeFqPKafdGJlBM0Ug+JBoLvEVkSe+RPPP+oEO/E8P4MpoAfg40R2h0tQr016JeeOJ4tkgIz/A9dPC8Sx6lG2tFVUAzh4o4+ArolySaI2+KPYcrMyCAUHJBKvakOj/j6L7kKVfNO3VSWumLaRIyBB2CfaWiiB5s7Unr94e5l0f9MPnYSohaeEU1bMdfvqw/8kcSDaiK3z/bRbVgkA+qepvkmw4HjgOMPLxHk6Ux5pWU8BkGQYlhtULq17Xth9RilVHoYy5vVsun1QddDf++65BWlDVxutM2QNDGx7KVOSq91lW6G5ot4GuCfi0LR76Lx0fhN5DtXoQ5tLZRl64RHaf8lebkD2IFfikO3SZ8jLevjpoXIwvk09wd5TGYdW0kuR/yka81+mEbN1ptZ/lMaMCg1Yg0//SaVxcBfy6RxEal/V9+dFyANn/aW4ejfWCi8Xnsl/zLdrjlV+nbPmPbuzpRSVH6fEdu3bsY32B7QnPaDT69Fr/2y7hpSx7FcDEfXMXGaCzLapCTmn2FZSCUcn1L+P0PXGNbz0rojuGXwx3I7tD2CQ07YNm42fJRx3utUuWkf1JjQ==
