kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgAusTZAVG6Wggdh1kbohSz5fZH7+GUalHurKkmMCmll2l4ACMcZw5aEw78gL2ZbbMvf7eWtFTOw2VItvNE3AlCMJmJSJb0+BA5gg0fDCWI9KJmmgMJaBVV0c7oK0x8dQ7ICUnQY8jRiE5TAy+1oefeSrvNVwStgph71dLqpqoLeA8DtUzKjO68pyxrVBuD4BrCBx0IjasLRT0xnbveiLu89UougeWwmBxodLBmS413GkT5PKuXrZE0KyNxXnze+nkK7QQL1pE0P7HWoFrKYveOOhfP+pkNq6eF+euA5tkiGfbB+CQu593GVjtYDyan9YgKoAA3lCzjq1LcaGEp3mcH04Tfpz6ouGIDWcarTImz6+wb8/rVg6YCxt9ZDg6HgqCKlIn30A6ufNJ67jCivJm3s4CjqXgKCNI/c+RSIAYk+XsBvCJSAvAXBKhTJGoYK3lkTScVrZf28lcOiraHaUc2HNECOfaQGCac5m1DCNB4yjfA+K4xfMcsSsNCmzm0vG/dfrEVBmiodxcOF09wfbxWCp4qh9IVzKXx7w5gR0BYDuggBoMV0bSxoKicRCn9yDcrQ7eWBST6M7M+fDxaRdwjVJcjmTTNju07N4fTZC3Qg54iCKZPc62NZuJD80JlA6Nte8vUH2qsxPNsPGxqoavtzvfrbI8zQKugtPjuMNgdZPyYeLTt6rsaLsZYfFiKqrhlYroVy
    admin-user: AgC4hf2hr+8NciU12labqZAWHeSIj9rL5mkypyN1PIBlT9O63/OmLUUomYoKUC1IxrsvRZu//or5qia/ayp2Tx90nQAs8YIVDgKSGiNt9VdNllBgktNRiOHKDVzfrZ1eALO6gk+5t91smiIatQEOOvNWJLKAD+Hz+mPIxX5P+/IEMwfG3sjPqrqotlr6T9GOoAZep1gUEL1AtoyEh/+qc9OPpU1/elc8T8Lk8dOlwHH+XBgzGnr0ExVOOtZUUjjNxVMT8KBGy1v4QbKGm6ujQXE/8FlNPrbU523vKfV/8xsqBVAWzyscQ5pe0TZ66gvY9I0HIpGugMRRg3AnU34Z/js5mV3QtZGg1YWDcXcnR6JX/adGjf6O/DZn/8uyj1LmeJZXw36tjcW9vTJ5R9mr/yuMX93LqD9R4E131k+96JxB6vhjx5lIyKAZoMK946gzGe2XbnrKUuB5GneMSy1VPcNJ6R1hemJEOuZPG7jTmoFX7hN7XaJPVAxyheFCebbuaBkcIh/aRbHHXqToTL1Hj8xHlbUrJlT9rz/olLDMka1ZwLRl4BMfBjxD52dXEqommIWZydchDStdx4pcyjJhVufr2hq1NNb+q8wZBI/1FwIvYkBZg/B+EtJH2ZYdipOxrCjyJOR90EIhIwgETAR6WkvnBT9/5S4NxXsU/Lgcf7yhJjs4hEgha60XPUQDdkv6B66Ams6H8A==
