kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgAf22w9QFKER2Gi6b19lpSN23iH8DDM98Zd4mHy2umlmaBQKG5RITwQMG37CRemXG3EgOT0+hdfouB0yzd/jFLHUs0Rq96acq1Ewfgfmr7ikVfz2NpXq1/lBQPXKNcbFLr2CvNC+VBlXIfOwTp6RwjBBx9z1cwIjuolQFZG0usEz+DDtdbglHPNNBlp2MXUvlVafzzZcnUrnQLlAemKAlk6vGnqimPFD4z5+dXaZwA0vBiaDNnl+h1xGVACeFpQ2RmwxXOi/Vy+oL0h7mtJFq+TKGk6APQ/smI3yU+h7hYfZUlyNtsP0olXO/h4ZN5N+Fb0rmXV0WKFB8JDl4OZ4FETD+yqZjuHBIqVC7QMsuEIBpGM0Zj0N7uO8RMo0aCS764QjBr560U7yq9xdBPJNzMpeOV3qq+XBtoZBVBqixzHVf4CNvKpuKyBeNppKAYjlPgB04tULaFuLr5bTMjF3oqOmVBm5eqJ0gXMGgTu0zqPspN/rBPdw67UaeCDSS246HcvMm90HPH46tEc2aEGzd/hUGkhWaocpTU8nCyJFaMepf7MVoLyC7d976kn0D3q6BixlUuSnedkihy9+iV6kKTpaV75hwMrlL6r3x6Hlt4eob0vh8mt7E61CWdEnx3f1tqb5m72ZW/9MbjwLg8lpU4sH0G9uTpkOSfF7BkpOupOfGXtmqn2yIGj8nuhWjesNQrGlo14
    admin-user: AgAcaM9KL5/zFEyWqN0xNcI/j7q2ADKIpBcrh/7K6k2NrMNtJenXoVwAaIFyVGTX/sgiE+2GONHg0u6U4mcApJYSoeC2p7bWosCO4wR9z76xwMh/igq+ZlGm6hpLUacGGGDKFHkvCuk2oOaVASEfcj0yuiyS0f1j45V3Lr3aR8pHQaO1P03KZKhX3q98TMzNziz/f3H/mHq3ZBR8rrnQJsRf1dgi386lsnPBrGfFb++7gmVUBLHSvYtOzIaYpdTcpm+TZ2xn6B34Sj9DI3Cb/7IHluBAx5ncXnfSwH1jO6u6Tv7AwkvrVbIZ9Sd/9Hk9K5kbbYHJv/CPU+rIPq+c4CytXNOQeLeMLZ8yN05JXY/gmp8pm2/SAZmehgsLw5e40T+YG78v5ngkgHRQHTsluj6aB3gO8cGPK/ubgUPP7A9RXuWkbvrZM1f/zCXI3Hg4RpOc2ujBxj+q8j9uSZ5hrS9326UHhFun2Sdb/fVqN+VOeTcWAZysOWhOE4vjTwJxMkA2lu/CWxqO0WytllLX/cIiJQ2ATfglyHeGdE3D096KXIwQjvni8thO5bXJDXZ03pr08QEeK3V1+OsclO+jzk3+VrqTkt39CNwJPuwxtVjxoAZhVJB5yG2AYoN40s2lY5/KlngA2fIY4UYmadjxBxhtEY686YBuqAUmpiHCqWVzi/TiQyqnVVyDsOFMAN2YkhULGBhFng==
