kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgA8yHFwRMKKA0z1++6ewjhGoFyOAzjv/IlJMSY0TW2Gb/vFtREH5W6KSOAj5Vt3Oi/o+r8ZXPWxPSCEaMxSruyALDLU0htvQ/4pD7aA5DZYjBR/5oMoK8IN5tE0Or3dOS9dH98sXMN/A1YecztdDA/om5FJNsNpcVpXPQKJ/HMf/UgIPK1Mm87JxxMkxewj267z2xG1JOwlX0Y389SIFyyORzGuxNNu1dX0VS318lcxR7GenOOMdnDm6PS6yPwKXIVBJwlLvTtpiV9pyeepYuu2bF0ZYTRl+9IlaoNifOpRFDnzHbfCKdMdIbLYe9W4QrkvjbVDIfP2aEq+WPXAM7oFttBfm1L1b+ykBxfsYW5H7imUSAoVBuc9gprPxelY5CgcFN45QRkL5A27yJNkvW6jr2QCfpC9AhHfudYiKT89JWpPvks/90LRAJl8D0MdLMVACDACGwXE/rhP/o1FT+vvzI8Ij7WB5UEyincFeeuPNhPT7k/a7AjgIbcx2KsMt/YDLdPKUZmvu0Cu9h9h//eRpqMwsGG9t9d9o718X47Jo8/rMIdkjoTaUwn9YiS/KDSTRbAIL3Ujc+2lAhxmiPyOaXTPLPo+noc3z/Ifvs5BYYM2ZQZIUaHZsImOC+Cczy1quikpA+PnuemohqSkZJU+uf5GXSjpcRshxf8V8KEm+8uqWcW706y+qTH1/C/rKgsYvPBJ
    admin-user: AgCMdZb312vINX++oxWjCkknuDTYO/ZKl5tNM6OZWuY6yx3EuCdPsHupUNC/x8Nn0XmpIS0vUk9hzQzBoS9b9vmUEFlqtDo+12hBXyE//qlk/5JXlLPj9udS6e4LmabunjWOFaqH/m2JE9nUyKiryWsnBlAlyjnKkY4CU4xYfUDfdkqZX47RPR/77+KvZCnzPe9GKfuAkqXyGJ+KJR9RsXZ9tU3GzmZuLrnZPj1pJBmS/lN/9hT5YZ9MQUig0tDnD9Vh3ENvACS7iJdE9VgwCKkO83PMKmc25EBvC8OzbdFPc7QNivXu+kUtGeUdezgHt+Tl476+6lYgY5B6yjwaJHmMz5bCJD1Pq5GPVjya/a9H51FlmrFQsxAOilY/6kLyWK4NEi1Um1myoVr7Kdh8xG1v0cw2syo2Awi1mtYwjVqWRGowxJHDbSi4UpsYhF4271Nm62LNGfkoi0gfWHIBPEEA+oxRh6eg1qLu6RCWLG/01bcPV2GLjsxcjxO6Zf4fF5vlKUGm4ZlpgRYXvH4GXpEYF83Y2+6x9zr9Khtxj2PPFB3+boXQRAC6zbXDXGPVfIG1qQEgra+yyVJRuN7d/B0AIQNJUSbKl2ux5aiXo5Ptl8BORJLIfIRl9LElNuMTnC3B7y0KWj7e/ZtnukjT+o2lVdlOzcRd0wl7jiT+Vp+cvBRm6GzDGTfamntZTz4x3tRBuLUJig==
