kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgA63DeJ0yZbFYfIvxJluUvtxsU+X5yQgKdsMOpJ3ZbeRWkmR49cMYfHTrMNH567CLvhw3i5X77zzKDY4XpO1XGhWpqIWrVi3EIsZP+wlOWjuwqk8BJl1shfC8idduwyRoe30XxDLlfEDa4ZS47NF7SjaqfLb660jITy0MEbQusCNcQ6tdBQSHFESsvETWaS1N65OGk0Xo+PriKgPasqJkxOuj6le3oG/CBZLaP6M57BfxMhCV8BXVzIJywr49N5007c8OWPIjcWZnbXsgeuTsg6Pwq4P8b4frQYSkqkFOYIPBI78hFvBnrCaVIrTdBvPlILpR0I7EuLe98Xr77XLk9i0OrYNQCMS9tfkvHHK25idayYhOqww7/68iN8RWHpbXNtGzL5YLhdbuG94sVJ6edz+JRuC/8ikbADUPc+/WHDZtNZbfXxecDHlH4OuCPjKyf9CH9AcKB1moju6SYEjR2OAVfprDrKyeXIKQDPTTcovV1y3RIHmlpJlDqBxcL2MzbwdTIpuzUF/qD7As9Xea9LuQwE6Vx/TUNI7/FSrtyHim0pnFT3KXn43oRTYCbI9T3jjhBV8vGlOebbrZkcwvpWSXsogS/hLud9HxWu5bPG8BbZGSR7SaoXkuuSS3fpyhgC1LIfJNdd3m9u9E7ra4xhvxQyJaQ7dKeEYXkm46KXFOJsvsC1pELJuj0Jed/s9mX8R6oa
    admin-user: AgBL33YQDRJ71LAx2KPjaw6dU4fXEIHdzpTv4aRLypHe9Kr1OxA7X/yQBY6sSV4F+2jFuMpfOGEyPg7QrPyMa8GdpHIf/q6FjX1W+0ZWTONwfetqtdmeG2p1eZzh4jWfSRQEda+fc4Q7PFGR+MGaAvS5x/lopM3Ta7obnfEG3r8VjpoOFtLMiISjqrkq55RcC7Kvske1Uz7cH/an/xuULM7C6fDiYBhMA80qZV/oGcEyS27jTC/AxrVB2+TIJiW8SWiVSyodbU1IBsUBtj93GrWnrnzJ2g2TaAq4YKQ18soDbwADM5ny1/jCNlqsVIHKypeN/OeRrLsAAcTfhPzZ/ectfKaiIslmSugB/d024bcwKVOSSFUeBBOKouPP/0/pxN9c4MVAdxMQsShPsh94zR2C4usYtRSakpk3TlY+i1VHVWpg3X3UvyCarjVJmjrLzG8a8dl9UFznQcGL4u3I8sfmZHKPqAUm7SqwzTm/VatYYgZ/9o6WP2FN5wNoh9naCDV73GyueRVdyHLF0reN2CoswH+v16yeHnBp7she/lP1LpPiB5nxhRGr4xmmMYhZYNyBQFr1/OBOVSYq71zbpFWH75op1nyAVQjWxKn6gzvIT/85yAvAw4xrk6HneklC8ENgsZuYaquu2DQqoU0d1CMqO+g+sBGGqOQG5XPtjjV724287MV17JYgeapR5/LOSoWWXbrK0w==
