kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgBcM0G0Mo/8rChLkTl54+v4bu7qpl54NXkON5b/CzH48J2ZbJrAY3yFY8QUb9WljVXWHZ5bDjwfcMX1dayJRqHH83aJXiFZmfwB0mZGS3xu4/ZoK7mhp/KfplFQPlx2h7cehc3mNYAaMspNLNfjJazAYhSlekHWw2zEGyVkUTXaG54puurzPoOZYy4fvA0+/ggibPewbOS1dbIdJV7aiKrEAePhWxrfny9INx0EOPwZa78QDB1LB5AJY7RHsi6duPU6IrX2viINNuAzFQza1vkFc9EzlNbj+CO42fGf/6NHZjykIX2P5RUTen89kGTHkJq2j8o3qFdbU4RNd4kMvNcxgxsL4z9IYxcZ/juQCkIGdR5eAo00yO4tAuQmJ8FudlVYB6q2rR5vUZlIau6QUX1KaNzNn/xjHzqhVWtIuoYB5iYsd5ii3hMyWmBiPVCwfJh1Lop9WiC1P06WA9ahUXTQNOpQk7KeT9qUYedpBMUNqm/WrOOxGogCiOwdyPZeo7kxf54vqypKtKfgVpOoPiuflGcfj2gQXbN+Fa770oPz1qAkaVUW9Bn/ijq5PkN1s1BqXUXSJjgF1DJ3R3ekoDEr9rre3ToRVqr3ozkId96KpnuZsOfXbiRNf3tbDSJm5WtVBJjJ/w3fy9H5XQH/B5NdExFcWqAkzvLilCo4H1MLBXWpiiUkICCO46YnpjluBK40BwBZ
    admin-user: AgCHDY0rm/0uRzgAC41sP+Q7wuElqBGgb1E7Z9873VYTen29rzZCYIKU8hH0uaoUJwIIDjMoAuBGvfN5q1dkZ/aKagjTaXxfMkjfaKHqaTynpfehF/gci2BnPLt7y5Of9xJgFvC5Z9TIcHZXERnOSyDVDfkVVoVrgQQqVXKb3unBIjMrTrpqzzBPwcil156ipmZt7ZCOzbMIRoLz8PdSsm51QF/Vc88Vw8EHL1UQkEgsZcv4DceAHPixyv/hqe0cNez4v7ogflpThoAoyDb2xOYvwt2TeQbKbyNdlAuNfhNdBvUXg9x/lQ8qI+zkBeiyzzw7uVb0PLvNH3Svm1E0N9e576oGdOEsgJGnQsNZyhXzvqZIsaYHemEKWNRD2psFSTVrbeH9FWYhFB0JOMm9EJtKwj2fIDLKQpmuKAfPMJ+C6uPr8SmEohE0RS4rhZHggZAYEXhV72C6bsLjwx5rhKddcst/RMvuNr1q8B8QMbOk9AUWUGawBb368FUajCByhr+TsU5fnBjB85AOzks8gp63sdePxENPNgLinTAy8CN1zHWNzjwE13O9M5Zv3NIfDf+bgw5aKtmO3ucHy5/Y8BxmvYrLTad5M1V4b6Qs00JPnrqRl11L9ZG3h4DtNvj+QGnSt85n0qvCiuDF2PVr/rvq/v+2lza8xv6z03g/ASPtTrrda3QGoVBFKPioWuN/iixhYPT3wA==
