kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgC2fxT8d5YzfuJYRzbd8JhPqeS7YOIKcBiGC1+R8deDpXeH7cDC2qiegMwkMlZIAwKFixyKULAqSk/4N3+2SM0rWAjyi8RJM8R6YsLs+H379TRNEbfMSTFKKSj1dIbHhraqfCR2KCV/ykuVTjhtJVw8NTNhxi+uR12kFfLtbqwuLyj/9ZAXtOzg6lInMqp2UZfcSr6XXTYyaQpGtCjDDneGE8yZtmDuhai5ZzsB06OWHuR9nKcSpWioSXefBp9II6OtLJK8wl0lV5rl9lECoT/rPSzrdBHsPZgvVsAVA/dhu2jwYUpWpIt6fHAinwi5F0SfSiYI0/CpuZmnJduuoO6JcRZ6ro+IGDQA/Oa4rLlqYMTG3n7NxZT3sASt95E06wMqZyKVrWZgS1mcrWw4GwbfiVs0PW/0qRYLL2iqfQxrz5hiarX/eCAG7gBXkS384igT9BjUnpiyqWIlX/Ik9xIyVJXtznZxCG5M2x1iJhkTLnh6uYhEmX5M/5mSqp78iWsmTq06ynu5QU59M7y2HaK4okqJdwPjmRNSLtxUUp8eBkG5SzRF5dUhZrq35NK+FPkoUK++uMya3TmRKt6htCKCi1HbIlh/AHP1brMNmc3SLwedK6xRWX9IFOoVtuK5RogGKAz2fcMjLxTxnIG60B6JjWYuzEkxp4ntjJC54ctu6iNyeb+pnZiEqGuPuaaHjJ/uEEBr
    admin-user: AgC52B5GFOoFZhK5aCK9TqADVPh1qOOuN6oHLvbJDav1qeRP9wTdo4Cz3NKWIdw5uHQ9qipTdXDFAijxLa/KRHeFwOcWFMGkQ82pkv3EMfxQ3GO6I7O+BNbhbvqNoLDO1sFqyFQW1X9nolS4bBz+TMgvwdRNzUn2aSmIn7tm06a1X69tkw1mhP7FQZzMsopbRu5uwaw7fxxJsijuCOFsqAQ2Y9TGStiCHPDPusvWYo35rWsPLKewXBFR/3gbHAgXtNhbO7R6Qa4/mwgZA4KP1POL/IfhdptwY9FKi7Xa3NMIYB9wS4yX/rAoWApDE+WyQoapZOmXuvAFpW38+5w9dq89kgn8mYTyi7tBvt3eAM1+wNZoU2k7t173xxZ3LIChEJPJzo/v0a0Rk/SsSqfnJE3onJd4UQeBdAL8DMkFsefnhmiVuHYRKnl06Ujf98c6SmWk3Xj0uVdqi8VlMBER2aL/m5OR3o6V3D7bD0VtuxFMLV2+aJl1klAVAnx00hcM3CRcIg2WtC/CTB39Xu0YNutEsTos+NevN3Aim/TjMvMdNy4qY9P+05cXMiQ8TAoe3Nr2qhax3bYf7fRLRrUuhefcudzlso9qcJwKDdrlJNJ6LT9Hv/hM3drJw61LQaiwZcP7WA7yF0RKjPSK4NopTQnc8bnsaINn0V/LCQ/DFmHKV1UHjhFSd0/BxjEE8LFgbeiWHpJivA==
