kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgCaFOSswL/VYUgNGhqAJ+2an01STw07gcTO3lU33vTrKykFG0CThbYNji9ueMfyGSAilRTKjDEzqW6GY4S+J9GDyVEU8AlV+Vaia+YhpHGHepbYBitKRyv3qgc+RH8VvnkmCHgxCYPYPsuYPafBhWVbymy3jXuivVcvLtKlUQeAy7/9uaMSbFvrv1DweJ7ZJfQJfAnr+L9zzS97/KwIXa8/KqUn6Pb8uTd+cIjueYKyP6qhnXWu8uxicPCjBOHdhbnmYJgmj8jU3iX6qkT1FN3lmfu6XSuuZg+XAC55+V/fX5NQaUapU4LVTmUZeg6j2sujgVPO/rJh6e4xqRhHmMOwPUahyqIqiM2DodUzoHivy/cl4yWZSPfJFYTZfdOsYv8vb3+doIwAMhNHOmRk5Df78NSqhSu6jKBsBlVqVLFxG/KKz/ADphHqLEcHEf3x+Tp5HqkBRlNK4/6YXi96ELzGvz8kXgQAAa1m5qbGffj1xSD/cVHUKTzwe06Cy3rM1XivLNCn9pLpL2b9qk20LcXK7ClYiPePFtz1EmImcUELqDQ42CevyN7JNFKTa+wbYdhVsxurx6N5HBiQllwAN2sKlvmPAgLW3gRdneTxDk8DEzJ4UeoEVfeGTpoMxrEe/YrJogUalAHxEqqAVdTVUrCQY4lzMk4seMx9SB+rWR3FjY5xB1mI9GNRcDFVrZ9ZJdIcktiI
    admin-user: AgBgjrO6Lpx/8RsPhYYgMYbI4AkfVUI7QSeSX+WIHAlUCAdU7BzL1P5Xz/BPRV/Ys1GHne9bHvYCLgcMCiAyxGdFYrjJQOayZjmSf4Jl9ES5pm1a1Ew7uuJ7QyQavTChttnFwViHILxCH/ogsFZfRh3tz5lYZ25J0MemtJyzCz7ziCxWvD69iixokBYbQ1IKGDtZtairV0nxz9BLCTrakTfHCCkhjzpRfSZlE9pxQHuqQOH44/hDaT+L+kgQTIzJj49LLBg7akCqJh6zyFz74/JZ5WQV7WbtT3JTurkhnCe88yGcnYEM7eD7tkb2+WTDn/2XuBeGf9r/Mp9spbgxwr+ybvzO50OWdBQU6i724CVhKC8cM6DlgPO3JiOLHyeejXEZN9PvDUF+J+XkqaT4AIqf31TE6BzeLruCbn+O9MMMZuLDmHTAtPSMd7tjd7sHSAK01JCOaml5B8BMMD8GO1EmZkFkqpEQ9dFgrqq167+77SYadqmK3Bcr7wRl1VMHRUbyQVtq3kRk/44leGTF8eW1roB/9BRPF8p39HPCNtD0jdD1d5SbESeroYYpMzV/pfvK1GliHcb69H8wGzSJ6jyVE3Z9qPjPOfCkJNdkWmkdD1+l9ag9cAHpz3jy6yDgMUI+B+7JV/MaDLs7XgFQEahJ5vIz4xX2HWeLDPd0o7dUnbfd7OTHSrOvmQj7B22kERJ8YpgJSA==
